<?php
function mainPage(){
exit('<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>注册服务</title><style>body {margin: 0;font-family: "Segoe UI", "Microsoft YaHei", sans-serif;background: linear-gradient(135deg, #0a0f1a, #1f2e45);min-height: 100vh;display: flex;align-items: center;justify-content: center;color: #fff;}.container {background: rgba(255,255,255,0.05);padding: 40px;border-radius: 12px;max-width: 600px;text-align: center;backdrop-filter: blur(8px);border: 1px solid rgba(255,255,255,0.2);box-shadow: 0 0 25px rgba(0,170,255,0.5);}h1 {font-size: 2em;background: linear-gradient(to right, #00c6ff, #0072ff);-webkit-background-clip: text;-webkit-text-fill-color: transparent;margin-bottom: 20px;}p {font-size: 1.1em;color: #d0eaff;line-height: 1.6;margin-bottom: 30px;}.plan {text-align: left;font-size: 1em;margin: 20px 0;color: #b8e0ff;}.plan ul {list-style: none;padding: 0;}.plan li {padding: 8px 0;position: relative;}.plan li::before {content: "✔";color: #00c6ff;margin-right: 10px;}.register-btn {margin-top: 20px;padding: 12px 24px;font-size: 1em;color: #fff;background-color: #1976D2; border: none;border-radius: 4px;cursor: pointer;transition: background-color 0.2s ease;}.register-btn:hover {background-color: #1565C0; }</style></head><body><div class="container"><h1>一键注册</h1><p>更新提示:我们很很高兴的宣布，现服务已限时开放新一批用户上车<br/>本次推出更多功能与优化，让您的体验更加流程、高效、稳定。</p><div class="plan"><ul><li>一键接入Linuxdo登录</li><li>一人一号,安全可控</li><li>智能化操作界面</li><li>账号密码只显示一次</li><li>热佬免费技术支持</li></ul></div><a href="/oauth2/login" class="register-btn">一键上车</a></div></body></html>');
}

function susscesPage($user,$passwd){
exit ('<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>恭喜注册成功</title><style>body {margin: 0;font-family: "Segoe UI", Helvetica, Arial, sans-serif;background-color: #f8f9fa;color: #333;}main {max-width: 800px;margin: 40px auto;padding: 20px;background: #fff;border-radius: 10px;box-shadow: 0 4px 12px rgba(0,0,0,0.05);}.intro h2 {font-size: 1.6em;margin-bottom: 15px;color: #1976D2; }.intro p {font-size: 1.05em;line-height: 1.6;margin-bottom: 15px;}.register-btn {margin-top: 20px;padding: 12px 24px;font-size: 1em;color: #fff;background-color: #1976D2; border: none;border-radius: 4px;cursor: pointer;transition: background-color 0.2s ease;}.register-btn:hover {background-color: #1565C0;}footer {text-align: center;padding: 15px;font-size: 0.9em;color: #777;border-top: 1px solid #e0e0e0;margin-top: 40px;}</style></head><body><main><div class="intro"><h2>恭喜注册成功</h2><h3>下面是你的用户名与密码,只显示一次，记得保存下来：</h3><p>登录使用用户名(注意大小写)，</p><p>用户名：' . $user. '，密码：' . $passwd .'</p><button class="register-btn">我已记住，跳转登录</button></div></main><footer>© 2077 pi.oldfriend.me, license under MIT.</footer></body></html>');
}

function stopPage(){
exit ('<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>服务状态通知</title><style>body {margin: 0;font-family: "Segoe UI", "Helvetica Neue", Arial, sans-serif;background: linear-gradient(135deg, #0f2027, #203a43, #2c5364);color: #fff;min-height: 100vh;display: flex;align-items: center;justify-content: center;}.container {background: rgba(255, 255, 255, 0.05);border: 1px solid rgba(255, 255, 255, 0.2);padding: 40px;border-radius: 12px;backdrop-filter: blur(10px);box-shadow: 0 0 20px rgba(0,150,255,0.5);max-width: 500px;text-align: center;}h1 {font-size: 2em;background: linear-gradient(to right, #00c6ff, #0072ff);-webkit-background-clip: text;-webkit-text-fill-color: transparent;margin-bottom: 20px;}p {font-size: 1.1em;line-height: 1.6;color: #d0eaff;}.icon {font-size: 50px;margin-bottom: 20px;color: #00c6ff;}.footer {margin-top: 20px;font-size: 0.9em;color: #9fcfff;}</style></head><body><div class="container"><div class="icon">⚙️</div><h1>此车已封车</h1><p>第一批用户已结束，此车暂时封车。暂停注册<br>已上车的用户继续在车上，不受影响。</p><div class="footer">之后看情况进行再开车门</div></div></body></html>');
}
?>